"""add groups courses and rels

Revision ID: 438234a9288d
Revises: dab564422998
Create Date: 2022-08-30 17:18:22.043905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438234a9288d'
down_revision = 'dab564422998'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
